config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  resources :boards, only: [] do
    resources :board_threads, only: [:show, :new, :create] do
      resources :thread_messages, only: [:new, :create]
    end
  end

  resources :users
  resources :personal_messages

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    default_scope { order(created_at: :desc) }

    scope :correspondents_of, lambda { |user|
        joins(:outcoming_messages).where(outcoming_messages: {user_to: user}).order(created_at: desc)
    }

    has_many :board_thread
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :redirect_if_authenticated, only: [:create, :new]
  before_action :authenticate_user!, only: [:edit, :destroy, :update]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    puts "\n\n\n", user_params, "\n\n"
    @user = User.new(user_params)
    @user.last_online = DateTime.now

    respond_to do |format|
      if @user.save
        login @user
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :avatar_url, :signature)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render partial: "shared/errors", locals: { object: user } %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, required: true %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Id:</strong>
    <%= user.id %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Signature:</strong>
    <%= user.signature %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= user.created_at %>
  </p>

  <p>
    <strong>Last login:</strong>
    <%= user.last_online %>
  </p>

  <p>
    <strong>Has permission:</strong>
    <%= user.has_permission ? 'yes' : 'no' %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to main", root_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>