config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  resources :boards, only: [] do
    resources :board_threads, only: [:show, :new, :create] do
      resources :thread_messages, only: [:new, :create]
    end
  end

  resources :users
  resources :personal_messages

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/board_thread.rb
class BoardThread < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :thread_messages

  default_scope { order(created_at: :desc) }

  def is_restricted?
    is_restricted
  end
end

app/controllers/board_threads_controller.rb
class BoardThreadsController < ApplicationController

  prepend_before_action :set_board_thread, only: %i[ show edit update destroy ]
  prepend_before_action :authenticate_user!, only: [:edit, :destroy, :update, :new, :create]
  append_before_action :authorize_user!

  # GET /board_threads or /board_threads.json
  def index
    @board_threads = BoardThread.all
  end

  # GET /board_threads/1 or /board_threads/1.json
  def show
  end

  # GET /board_threads/new
  def new
    @board_thread = BoardThread.new
  end

  # GET /board_threads/1/edit
  def edit
  end

  # POST /board_threads or /board_threads.json
  def create
    @board_thread = BoardThread.new(board_thread_params)

    respond_to do |format|
      if @board_thread.save
        format.html { redirect_to board_thread_url(@board_thread), notice: "Board thread was successfully created." }
        format.json { render :show, status: :created, location: @board_thread }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_threads/1 or /board_threads/1.json
  def update
    respond_to do |format|
      if @board_thread.update(board_thread_params)
        format.html { redirect_to board_thread_url(@board_thread), notice: "Board thread was successfully updated." }
        format.json { render :show, status: :ok, location: @board_thread }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_threads/1 or /board_threads/1.json
  def destroy
    @board_thread.destroy

    respond_to do |format|
      format.html { redirect_to board_threads_url, notice: "Board thread was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def authorize_user!
      if !@board_thread.is_restricted
        return
      end
      if !user_signed_in?
        return authenticate_user!
      end
      if !current_user.has_permission
        redirect_to root_path, alert: "You have no permission to this thread."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_board_thread
      @board_thread = BoardThread.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_thread_params
      params.require(:board_thread).permit(:id, :name, :description, :board_id, :is_restricted)
    end
end

app/helpers/board_threads_helper.rb
module BoardThreadsHelper
end

app/views/board_threads/_board_thread.html.erb
<div id="<%= dom_id board_thread %>">
  <p>
    <h2><%= board_thread.board.name %>/<%= board_thread.name %></h2>
    <strong><%= board_thread.description %></strong>
  </p>
</div>

app/views/board_threads/_form.html.erb
<%= form_with(model: board_thread) do |form| %>
  <% if board_thread.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board_thread.errors.count, "error") %> prohibited this board_thread from being saved:</h2>

      <ul>
        <% board_thread.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :forum_id, style: "display: block" %>
    <%= form.number_field :forum_id %>
  </div>

  <div>
    <%= form.label :is_restricted, style: "display: block" %>
    <%= form.check_box :is_restricted %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/board_threads/edit.html.erb
<h1>Editing board thread</h1>

<%= render "form", board_thread: @board_thread %>

<br>

<div>
  <%= link_to "Show this board thread", @board_thread %> |
  <%= link_to "Back to board threads", board_threads_path %>
</div>

app/views/board_threads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Board threads</h1>

<div id="board_threads">
  <% @board_threads.each do |board_thread| %>
    <%= render board_thread %>
    <p>
      <%= link_to "Show this board thread", board_thread %>
    </p>
  <% end %>
</div>

<%= link_to "New board thread", new_board_thread_path %>

app/views/board_threads/new.html.erb
<h1>New board thread</h1>

<%= render "form", board_thread: @board_thread %>

<br>

<div>
  <%= link_to "Back to board threads", board_threads_path %>
</div>

app/views/board_threads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board_thread %>

<div>
  <% @board_thread.thread_messages.each do |message| %>
  <div class="message">
  <p><a href="<%= user_path(message.user) %>"><%= message.user.username %></a> @ <%= message.created_at %></p>
  <p><%= message.message %></p>
    <% if message.user.signature %>
    <br>
    <p><%= message.user.signature %></p>
    <% end %>
    <% if message.image.attached? %>
    <%= image_tag url_for(message.image) %>
    <% end %>
    </div>
  <% end %>
  <a href="<%= new_board_board_thread_thread_message_path(@board_thread.board, @board_thread) %>">Add message</a>
</div>