config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  resources :boards, only: [] do
    resources :board_threads, only: [:show, :new, :create] do
      resources :thread_messages, only: [:new, :create]
    end
  end

  resources :users
  resources :personal_messages

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/thread_message.rb
class ThreadMessage < ApplicationRecord
  belongs_to :user
  belongs_to :board_thread
  has_one_attached :image
  
  default_scope { order(:created_at) }
end

app/controllers/thread_messages_controller.rb
class ThreadMessagesController < ApplicationController
  prepend_before_action :set_thread_message, only: %i[ show edit update destroy ]
  prepend_before_action :authenticate_user!, only: [:edit, :destroy, :update, :new, :create]
  append_before_action :authorize_user!

  # GET /thread_messages or /thread_messages.json
  def index
    @thread_messages = ThreadMessage.all
  end

  # GET /thread_messages/1 or /thread_messages/1.json
  def show
  end

  # GET /thread_messages/new
  def new
    @thread_message = ThreadMessage.new
    @board = Board.find(params[:board_id])
    @board_thread = BoardThread.find(params[:board_thread_id])
  end

  # GET /thread_messages/1/edit
  def edit
  end

  # POST /thread_messages or /thread_messages.json
  def create
    puts "\n\n\nat least here\n\n"

    @board = Board.find(params[:board_id])
    @board_thread = BoardThread.find(params[:board_thread_id])

    @thread_message = ThreadMessage.new(thread_message_params)
    @thread_message.user = current_user
    @thread_message.board_thread = @board_thread

    respond_to do |format|
      if @thread_message.save
        format.html { redirect_to board_board_thread_url(@board, @board_thread), notice: "Thread message was successfully created." }
        format.json { render :show, status: :created, location: @thread_message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thread_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thread_messages/1 or /thread_messages/1.json
  def update
    respond_to do |format|
      if @thread_message.update(thread_message_params)
        format.html { redirect_to thread_message_url(@thread_message), notice: "Thread message was successfully updated." }
        format.json { render :show, status: :ok, location: @thread_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thread_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thread_messages/1 or /thread_messages/1.json
  def destroy
    @thread_message.destroy

    respond_to do |format|
      format.html { redirect_to thread_messages_url, notice: "Thread message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thread_message
      @thread_message = ThreadMessage.find(params[:id])
      @board = Board.find(params[:board_id])
      @board_thread = BoardThread.find(params[:board_thread_id])
    end

    # Only allow a list of trusted parameters through.
    def thread_message_params
      params.require(:thread_message).permit(:user_id, :board_thread_id, :message, :created_at, :updated_at, :image)
    end

    def authorize_user!
      if @thread_message.present?
        if !@thread_message.board_thread.is_restricted
          return
        end
      else
        board_thread = BoardThread.find(params[:board_thread_id])
        if !board_thread.is_restricted
          return
        end
      end
      if !user_signed_in?
        return authenticate_user!
      end
      if !current_user.has_permission
        redirect_to root_path, alert: "You have no permission to this thread."
      end
    end
end

app/helpers/thread_messages_helper.rb
module ThreadMessagesHelper
end

app/views/thread_messages/_form.html.erb
<%= form_with(model: thread_message, url: board_board_thread_thread_messages_path) do |form| %>
  <% if thread_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thread_message.errors.count, "error") %> prohibited this thread_message from being saved:</h2>

      <ul>
        <% thread_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/thread_messages/_thread_message.html.erb
<div id="<%= dom_id thread_message %>">
  <p>
    <strong>User:</strong>
    <%= thread_message.user_id %>
  </p>

  <p>
    <strong>Thread:</strong>
    <%= thread_message.board_thread_id %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= thread_message.message %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= thread_message.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= thread_message.updated_at %>
  </p>

</div>

app/views/thread_messages/edit.html.erb
<h1>Editing thread message</h1>

<%= render "form", thread_message: @thread_message %>

<br>

<div>
  <%= link_to "Show this thread message", @thread_message %> |
  <%= link_to "Back to thread messages", thread_messages_path %>
</div>

app/views/thread_messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Thread messages</h1>

<div id="thread_messages">
  <% @thread_messages.each do |thread_message| %>
    <%= render thread_message %>
    <p>
      <%= link_to "Show this thread message", thread_message %>
    </p>
  <% end %>
</div>

<%= link_to "New thread message", new_thread_message_path %>

app/views/thread_messages/new.html.erb
<h1>New thread message</h1>

<%= render "form", thread_message: @thread_message %>

<br>

<div>
  <%= link_to "Back", board_board_thread_path(@board, @board_thread) %>
</div>

app/views/thread_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thread_message %>

<div>
  <%= link_to "Edit this thread message", edit_thread_message_path(@thread_message) %> |
  <%= link_to "Back to thread messages", thread_messages_path %>

  <%= button_to "Destroy this thread message", @thread_message, method: :delete %>
</div>