config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  resources :boards, only: [] do
    resources :board_threads, only: [:show, :new, :create] do
      resources :thread_messages, only: [:new, :create]
    end
  end

  resources :users
  resources :personal_messages

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :user_from, :class_name => 'User', :foreign_key => 'user_from_id', inverse_of: :outcoming_messages
  belongs_to :user_to, :class_name => 'User', :foreign_key => 'user_to_id', inverse_of: :incoming_messages

  default_scope { order(created_at: :desc) }
  scope :messages_of, lambda { |user|
    where(user_from: user.id).or(user_to: user.id).order(created_at: :desc)
  }

  scope :messages_received_by, lambda { |user|
    where(user_to: user.id)
  }
  def set_seen_by_dialog(user_to, user_from)
    by_receiver.update_all(was_seen: true)
  end

  def was_seen?
    return was_seen
  end

end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :set_personal_message, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /personal_messages or /personal_messages.json
  def index
    @personal_messages = PersonalMessage.all
  end

  # GET /personal_messages/1 or /personal_messages/1.json
  def show
  end

  # GET /personal_messages/new
  def new
    @personal_message = PersonalMessage.new
  end

  # GET /personal_messages/1/edit
  def edit
  end

  # POST /personal_messages or /personal_messages.json
  def create
    @personal_message = PersonalMessage.new(personal_message_params)

    respond_to do |format|
      if @personal_message.save
        format.html { redirect_to personal_message_url(@personal_message), notice: "Personal message was successfully created." }
        format.json { render :show, status: :created, location: @personal_message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personal_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_messages/1 or /personal_messages/1.json
  def update
    respond_to do |format|
      if @personal_message.update(personal_message_params)
        format.html { redirect_to personal_message_url(@personal_message), notice: "Personal message was successfully updated." }
        format.json { render :show, status: :ok, location: @personal_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personal_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_messages/1 or /personal_messages/1.json
  def destroy
    @personal_message.destroy

    respond_to do |format|
      format.html { redirect_to personal_messages_url, notice: "Personal message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_message
      @personal_message = PersonalMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def personal_message_params
      params.require(:personal_message).permit(:user_from_id, :user_to_id, :message, :created_at)
    end
end

app/helpers/personal_messages_helper.rb
module PersonalMessagesHelper
end

app/views/personal_messages/_form.html.erb
<%= form_with(model: personal_message) do |form| %>
  <% if personal_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(personal_message.errors.count, "error") %> prohibited this personal_message from being saved:</h2>

      <ul>
        <% personal_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_from_id, style: "display: block" %>
    <%= form.number_field :user_from_id %>
  </div>

  <div>
    <%= form.label :user_to_id, style: "display: block" %>
    <%= form.number_field :user_to_id %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/personal_messages/_personal_message.html.erb
<div id="<%= dom_id personal_message %>">
  <p>
    <strong>User from:</strong>
    <%= personal_message.user_from_id %>
  </p>

  <p>
    <strong>User to:</strong>
    <%= personal_message.user_to_id %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= personal_message.message %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= personal_message.created_at %>
  </p>

</div>

app/views/personal_messages/edit.html.erb
<h1>Editing personal message</h1>

<%= render "form", personal_message: @personal_message %>

<br>

<div>
  <%= link_to "Show this personal message", @personal_message %> |
  <%= link_to "Back to personal messages", personal_messages_path %>
</div>

app/views/personal_messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Personal messages</h1>

<div id="personal_messages">
  <% @personal_messages.each do |personal_message| %>
    <%= render personal_message %>
    <p>
      <%= link_to "Show this personal message", personal_message %>
    </p>
  <% end %>
</div>

<%= link_to "New personal message", new_personal_message_path %>

app/views/personal_messages/new.html.erb
<h1>New personal message</h1>

<%= render "form", personal_message: @personal_message %>

<br>

<div>
  <%= link_to "Back to personal messages", personal_messages_path %>
</div>

app/views/personal_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @personal_message %>

<div>
  <%= link_to "Edit this personal message", edit_personal_message_path(@personal_message) %> |
  <%= link_to "Back to personal messages", personal_messages_path %>

  <%= button_to "Destroy this personal message", @personal_message, method: :delete %>
</div>